service: minidropbox

custom:
  bucket: minidropboxserverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  s3fetch:
    handler: dropbox/s3fetch.s3fetch
    environment:
      BUCKET: ${self:custom.bucket}
    events:
      - http:
          path: dropbox
          method: post
          cors: true
  read:
      handler: dropbox/read.read
      events:
        - http:
            path: dropbox
            method: get
            cors: true
  delete:
      handler: dropbox/delete.delete
      events:
        - http:
            path: dropbox/{name}
            method: delete
            cors: true

resources:
  Resources:
    MiniDropboxDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: 'Retain'
      Properties:
        AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
        KeySchema:
        - AttributeName: name
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'minidropbox'

